### ISSUE TITLE
No Batt is intermittently displayed even with battery installed

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#67] opened 2019-07-05 23:50 UTC
Even with battery installed, No Batt is intermittently displayed in place of the battery % and voltage in the bottom right corner of the main screen.
Forum thread, started in early May: http://forum.krontech.ca/index.php?topic=468.0

**Comment by oskirby** [comment] 2019-07-13 21:36
I am not able to reproduce this issue, I suspect that the user may have a camera with poorly positioned battery terminals and that it seems to be a hardware problem.

**Comment by oskirby** [comment] 2019-07-23 00:41
Closing this issue on the assumption that its a hardware fault.

**Closed by oskirby** 2019-07-23 00:41 UTC
